#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Sun Nov 17 17:42:25 +03 2024
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim tb_rege_behav -key {Behavioral:sim_1:Functional:tb_rege} -tclbatch tb_rege.tcl -view /home/it/eda_training/Digital_System_Design/Labs/Lab04/project_1/tb_flipflop_behav.wcfg -view /home/it/eda_training/Digital_System_Design/Labs/Lab04/project_1/tb_flipflop_behav1.wcfg -log simulate.log"
xsim tb_rege_behav -key {Behavioral:sim_1:Functional:tb_rege} -tclbatch tb_rege.tcl -view /home/it/eda_training/Digital_System_Design/Labs/Lab04/project_1/tb_flipflop_behav.wcfg -view /home/it/eda_training/Digital_System_Design/Labs/Lab04/project_1/tb_flipflop_behav1.wcfg -log simulate.log

